# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Azure Resources and Application
# ----------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "FunctionDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include:
  #    - 'src/Functions.Demo/*'
  #   exclude:
  #     - '**/*.md'

parameters:
  - name: deployQA
    displayName: Deploy to QA
    type: boolean
    default: false
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false
  - name: runPsRuleScan
    displayName: Run PSRule Bicep Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if eq(lower(parameters.deployQA), 'false') }}:
  - template: pipes/infra-and-function-pipe.yml
    parameters:
      variableGroupName: 'FunctionDemo'
      environments: ['DEMO']
      projectDirectory: 'src/AzureFunctionsDemo'
      runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
      runPsRuleScan: ${{ parameters.runPsRuleScan }}
- ${{ if eq(lower(parameters.deployQA), 'true') }}:
  - template: pipes/infra-and-function-pipe.yml
    parameters:
      variableGroupName: 'FunctionDemo'
      environments: ['DEMO','QA']
      projectDirectory: 'src/AzureFunctionsDemo'
      runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
      runPsRuleScan: ${{ parameters.runPsRuleScan }}
